export { isNativeApp, getPlatform, isIOS, isAndroid, isWeb, getAssetUrl } from './env'
export { saveSecure, loadSecure, removeSecure, clearAllData } from './storage'
export { setOGMeta, resetOGMeta } from './og'
export { validateContent, getFallbackContent } from './validator'
export { getDailyQuote, getRandomQuote, getQuotesCount } from './dailyQuotes'
export type { DailyQuote } from './dailyQuotes'
